### CLEANUP ###
- name: Copy the cleanup script.
  template:
    src: template-cleanup-alpine.sh.j2
    dest: /tmp/template-cleanup.sh
    mode: a+x
  when: iserver_is_template
  tags:
    - vanilla

- name: Run the cleanup script for VM templates (only once).
  shell: /tmp/template-cleanup.sh
  args:
    creates: /etc/.template-cleanup.done
  when: iserver_is_template
  tags:
    - vanilla
