---
# tasks file for ansible-initial-server
## TODO:
## - check that it works with a default Ubuntu 18.04 ISO server install (probably using 'su' is not needed)

# For this block we use 'su' on first-run, because root cannot ssh into the server.
- name: KICKSTART (Debian or Ubuntu)
  block:
  - name: Ensure that python-apt and sudo is installed.
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python-apt
      - sudo

  - name: Ensure that sudo is installed.
    openbsd_pkg:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - sudo

  ### SUDOERS ###
  - name: Check if iserver_user exists.
    shell: id -u "{{ iserver_user }}" > /dev/null 2>&1
    ignore_errors: True
    changed_when: false
    register: user_exists

  - name: Add the default user with passwordless sudo to sodoers.d
    template:
      src: default-user.j2
      dest: /etc/sudoers.d/default-user
      mode: 0440
    when: user_exists is succeeded

  ## End of block KICKSTART
  become: true
  become_method: "{{ iserver_become }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - vanilla

- name: KICKSTART (OpenBSD)
  block:
  ### SUDOERS ###
  - name: Check if iserver_user exists.
    shell: id -u "{{ iserver_user }}" > /dev/null 2>&1
    ignore_errors: True
    changed_when: false
    register: user_exists

  - name: Add the default user with passwordless doas.
    template:
      src: doas.conf.j2
      dest: /etc/doas.conf
      mode: 0440
    when: user_exists is succeeded

  ## End of block KICKSTART
  become: true
  become_method: doas
  when: ansible_distribution == 'OpenBSD'
  tags:
    - vanilla

## Now that the default user can do passwordless sudo, run the rest with sudo.
- name: MAIN
  block:
  - name: Reset SSH connection to allow user changes to affect 'current login user'.
    meta: reset_connection
    tags:
      - vanilla

  ### BASE PACKAGES ###
  - include_tasks: packages-debian-ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    tags:
      - vanilla

  - include_tasks: packages-openbsd.yml
    when: ansible_distribution == 'OpenBSD'
    tags:
      - vanilla

  ### NETWORKING ###
  - name: Copy original /etc/issue (once).
    command: touch -a /etc/issue && cp /etc/issue /etc/issue.original
    args:
      creates: /etc/issue.original

  - name: Set hostname.
    hostname:
      name: "{{ iserver_hostname }}"
    register: apply_network_config
    tags:
      - vanilla

  - include_tasks: networking-debian.yml
    when: ansible_distribution == 'Debian'
    tags:
      - vanilla

  - include_tasks: networking-ubuntu.yml
    when: ansible_distribution == 'Ubuntu'
    tags:
      - vanilla

  - include_tasks: networking-openbsd.yml
    when: ansible_distribution == 'OpenBSD'
    tags:
      - vanilla

  - name: Copy original hosts file to back it up (once).
    command: cp /etc/hosts /etc/hosts.original
    args:
      creates: /etc/hosts.original
    tags:
      - vanilla

  - name: Create new hosts file.
    template:
      src: hosts.j2
      dest: /etc/hosts
    register: apply_network_config
    tags:
      - vanilla

  - name: Apply network configuration changes (Debian/Ubuntu).
    service:
      name: systemd-logind
      state: restarted
    when: apply_network_config is changed and ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
    tags:
      - vanilla

  - name: Apply network configuration changes (OpenBSD).
    command: sh /etc/netstart
    when: apply_network_config is changed and ansible_distribution == 'OpenBSD'
    tags:
      - vanilla

  ### SSH ###
  - name: Ensure, that the default user has an SHH authorized key.
    authorized_key:
      user: "{{ iserver_user }}"
      state: present
      key: "{{ iserver_sshkey }}"
    when: user_exists is succeeded
    tags:
      - vanilla

  #'UseDNS no' avoids login delays when the remote client's DNS cannot be resolved
  - name: Disallow root SSH access, only allow SSH key login; UseDNS no.
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
      - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
      - { regexp: '^UseDNS', line: 'UseDNS no' }
      - { regexp: '^Banner', line: 'Banner {{ iserver_ssh_banner }}' }
      - { regexp: '^Port', line: 'Port {{ iserver_ssh_port }}' }
    register: restart_ssh
    tags:
      - vanilla

  - name: Add a warning banner, shown before SSH login.
    copy:
      src: issue.net
      dest: "{{ iserver_ssh_banner }}"
    when: iserver_ssh_banner != "none"

  - name: Restart SSH.
    service:
      name: ssh
      state: restarted
    when: restart_ssh is changed
    tags:
      - vanilla

  - include_tasks: ssh-host-keygen.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  ### CUSTOMIZE ###
  - name: Set timezone.
    timezone:
      name: "{{ iserver_timezone }}"
    tags:
      - vanilla

  - include_tasks: customize-debian-ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include_tasks: customize-openbsd.yml
    when: ansible_distribution == 'OpenBSD'

  ### CLOUD ###
  - include_tasks: serialconsole-debian-ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    tags:
      - vanilla

  - include_tasks: serialconsole-openbsd.yml
    when: ansible_distribution == 'OpenBSD'
    tags:
      - vanilla

  - include_tasks: swapfile-ubuntu.yml
    when: ansible_distribution == 'Ubuntu'

  # GROW PARTITION
  - include_tasks: growpartition-debian-ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  ### CLEANUP ###
  - include_tasks: cleanup-debian-ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  # or use '*'
  - name: Prevent password authentication for root.
    user:
      name: root
      password: '!'
    tags:
      - vanilla
  ## End of block MAIN
  become: true
