---
# MAIN tasks file for ansible-initial-server

## TODO: see also individual TODOs in files
## - check that it works with a default Ubuntu 18.04 ISO server install (probably using 'su' is not needed)
## - use Ansible handlers for restarting services (instaed of restarting inline, partially done)

- name: Initial Setup - Debian, Ubuntu.
  import_tasks: initial-setup-debian-ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - debuntu

- name: Initial Setup - OpenBSD.
  import_tasks: initial-setup-openbsd.yml
  when: ansible_distribution == 'OpenBSD'
  tags:
    - openbsd

- name: Initial Setup - Alpine.
  import_tasks: initial-setup-alpine.yml
  when: ansible_distribution == 'Alpine'
  tags:
    - alpine
