---
# MAIN tasks file for ansible-initial-server

## TODO:
## - check that it works with a default Ubuntu 18.04 ISO server install (probably using 'su' is not needed)
## - ADD script: OpenBSD - generate new SSH host keys on first boot to avoid duplicates in cloned VMs
## - see individual TODOs in files
## - use Ansible handlers for restarting services (instaed of restarting inline)

- name: Initial Setup - Debian, Ubuntu.
  import_tasks: initial-setup-debian-ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deblike

- name: Initial Setup - OpenBSD.
  import_tasks: initial-setup-openbsd.yml
  when: ansible_distribution == 'OpenBSD'
  tags:
    - openbsd

- name: Initial Setup - Alpine.
  import_tasks: initial-setup-alpine.yml
  when: ansible_distribution == 'Alpine'
  tags:
    - alpine
