### NETWORKING ###

## TODO: Test static IP, possibly a route via main host IP?
# - Add a route via {{ iserver_host_main_ip }}
# - check:
#   cat /etc/hostname.vio0
#   cat /etc/mygate
#   cat /etc/resolv.conf
#   ifconfig
#   netstat -rn
#   sh /etc/netstart
# - test in Proxmox

- name: Ensure that DHCP is configured.
  copy:
    src: hostname-openbsd-dhcp
    dest: /etc/hostname.{{ iserver_obsd_interface }}
  notify:
    - Apply Network Settings
  when: not set_fixed_IP

- name: Ensure that DNS nameservers are configured.
  lineinfile:
    path: /etc/resolv.conf
    state: present
    regexp: '^nameserver \s'
    line:   'nameserver {{ item }}'
  with_items: "{{ iserver_nameservers }}"
  notify:
    - Apply Network Settings
  when: set_fixed_IP

- name: Ensure that static IP is configured.
  template:
    src: hostname-openbsd.j2
    dest: /etc/hostname.{{ iserver_obsd_interface }}
  notify:
    - Apply Network Settings
  when: set_fixed_IP

- name: Ensure that static IP gateway is configured.
  template:
    src: mygate-openbsd.j2
    dest: /etc/mygate
  notify:
    - Apply Network Settings
  when: set_fixed_IP
