### NETWORKING ###

## TODO:
# - Add a route via {{ iserver_host_main_ip }}
# - use handler for apply_network_config
# - test in Proxmox

- name: Set fixed IP address.
  template:
    src: hostname.{{ iserver_obsd_interface }}.j2
    dest: /etc/hostname.{{ iserver_obsd_interface }}
  register: apply_network_config
  when: set_fixed_IP
  tags:
    - vanilla

- name: Set fixed IP gateway.
  template:
    src: mygate-openbsd.j2
    dest: /etc/mygate
  register: apply_network_config
  when: set_fixed_IP
  tags:
    - vanilla
