### NETWORKING ###
# OpenBSD

## TODO: Test static IP, possibly a route via main host IP?
# - Add a route via {{ iserver_host_main_ip }}
# - check:
#   cat /etc/hostname.vio0
#   cat /etc/mygate
#   cat /etc/resolv.conf
#   ifconfig
#   netstat -rn
#   sh /etc/netstart
# - test in Proxmox

- name: Copy original /etc/gettytab (once).
  command: cp /etc/gettytab /etc/gettytab.original
  args:
    creates: /etc/gettytab.original

- name: Copy script which will display IP and SSH fingerprint before login.
  template:
    src: show-ip-adress-openbsd.py.j2
    dest: /usr/local/bin/show-ip-address.py
    mode: a+x

- name: Enable the show-ip-address script to autostart.
  blockinfile:
    path: "/etc/rc.local"
    create: yes
    block: |
      if [ -x /usr/local/bin/show-ip-address.py ]; then
        echo "updating display of IP and SSH fingerprint."
        /usr/local/bin/show-ip-address.py
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - IP"

- name: Ensure that DHCP is configured.
  copy:
    src: hostname-openbsd-dhcp
    dest: /etc/hostname.{{ iserver_obsd_interface }}
  notify:
    - Apply Network Settings
  when: not iserver_static_ip
  tags:
    - vanilla

- name: Ensure that DNS nameservers are configured.
  lineinfile:
    path: /etc/resolv.conf
    state: present
    regexp: '^nameserver \s'
    line:   'nameserver {{ item }}'
  with_items: "{{ iserver_nameservers }}"
  notify:
    - Apply Network Settings
  when: iserver_static_ip
  tags:
    - vanilla

- name: Ensure that static IP is configured.
  template:
    src: hostname-openbsd.j2
    dest: /etc/hostname.{{ iserver_obsd_interface }}
  notify:
    - Apply Network Settings
  when: iserver_static_ip
  tags:
    - vanilla

- name: Ensure that static IP gateway is configured.
  template:
    src: mygate-openbsd.j2
    dest: /etc/mygate
  notify:
    - Apply Network Settings
  when: iserver_static_ip
  tags:
    - vanilla
