  ### BASE PACKAGES ###
  # replaces sources.list repos, if iserver_repos has repos defined.
  - name: Move original /etc/apk/repositories to back it up (once).
    command: mv /etc/apk/repositories /etc/apk/repositories.original
    args:
      creates: /etc/apk/repositories.original
    when: iserver_repos[0] != "undefined"

  - name: Add a set of specified repos into /etc/apk/repositories.
    lineinfile:
      path: /etc/apk/repositories
      state: present
      create: yes
      regexp: "^{{ item }}"
      line: "{{ item }}"
    loop: "{{ iserver_repos }}"
    when: iserver_repos[0] != "undefined"

  - name: Ensure, that all packages are updated and upgraded.
    apk:
      update_cache: yes
      upgrade: yes
    tags:
      - vanilla

  - name: Ensure that initial packages are installed.
    apk:
      name: "{{ iserver_alpine_packages }}"
      state: present
