  ### BASE PACKAGES ###
  # replaces sources.list repos, if iserver_repos has repos defined.
  - name: Move original /etc/apt/sources.list to back it up (once).
    command: mv /etc/apt/sources.list /etc/apt/sources.list.original
    args:
      creates: /etc/apt/sources.list.original
    when: iserver_repos[0] != "undefined"

  # this requires python-apt.
  # at least two repos need to be defined. repos are added to sources.list.d/
  - name: Add a set of specified repositories into sources list.
    apt_repository:
      repo: "{{ item }}"
      state: present
    loop: "{{ iserver_repos }}"
    when: iserver_repos[0] != "undefined"

  # so that Ubuntu will not complain about missing sources.list
  - name: Ensure that there is at least a sources.list file placeholder.
    copy:
      content: "# Ansible managed # active repos are in /etc/apt/sources.list.d/*"
      dest: /etc/apt/sources.list
      force: no

  - name: Ensure, that all packages are updated and upgraded.
    apt:
      upgrade: "yes"
      update_cache: yes
      cache_valid_time: 86400 #One day
    tags:
      - vanilla

  - name: Ensure that initial packages are installed.
    apt:
      name: "{{ iserver_packages }}"
      state: present
