# SSH-HOST-KEYGEN (for KVM template)

# TODO test with OpenBSD
- name: Copy script for OpenSSH Server Key Generation.
  copy:
    src: ssh-host-keygen.sh
    dest: /usr/local/bin/ssh-host-keygen.sh
    mode: a+x
  register: enable_ssh_host_keygen

- name: Enable the ssh-host-keygen to autostart.
  blockinfile:
    path: "/etc/rc.local"
    create: yes
    block: |
      if [ -x /usr/local/bin/ssh-host-keygen.sh ]; then
        /usr/local/bin/ssh-host-keygen.sh
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Create a file so that ssh-host-keygen will run once.
  file:
    path: /etc/run-ssh-host-keygen-once
    state: touch
  when: enable_ssh_host_keygen is changed
