# DISABLE SWAPFILE
# Ubuntu

# Ubuntu 'server' uses /swapfile
- name: Disable swap if /swapfile exists.
  command: swapoff -a
  args:
    removes: /swapfile

# Ubuntu 'live-server' uses /swap.img
- name: Disable swap if /swap.img exists.
  command: swapoff -a
  args:
    removes: /swap.img

- name: Ensure swapfile is disabled in /etc/fstab.
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: absent

- name: Ensure swap.img is disabled in /etc/fstab.
  mount:
    name: none
    src: /swap.img
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: absent

- name: Ensure swapfile doesn't exist.
  file:
    path: /swapfile
    state: absent

- name: Ensure swap.img doesn't exist.
  file:
    path: /swap.img
    state: absent
