---
# handlers file for ansible-initial-server

# Alpine
# Ensure that local auto-start service is enabled 
# Used to start ssh-host-keygen.sh on first boot and the auto-growpart script
- name: Activate Autostart
  service:
    name: local
    runlevel: default
    enabled: yes
  become: true
